from __future__ import annotations

from datetime import date
from pathlib import Path

import _common
import session_context
from helpers import Git, RunHook

BEFORE = date(2026, 9, 13)
AFTER = date(2026, 11, 1)


def _context(run_hook: RunHook, repo: Path, *, today: date = BEFORE, mode: str = "fast") -> str:
    res = run_hook(
        session_context.main,
        {"session_id": "s1", "source": "startup"},
        env={"CLAUDE_PROJECT_DIR": str(repo), "CLAUDE_GATE": mode},
        today=today,
    )
    assert res.code == 0
    out = res.json()["hookSpecificOutput"]
    assert out["hookEventName"] == "SessionStart"
    text = out["additionalContext"]
    assert isinstance(text, str)
    return text


def test_context_lists_the_rules(run_hook: RunHook, git_repo: Path) -> None:
    text = _context(run_hook, git_repo)
    assert "Never push" in text
    assert "No AI attribution" in text
    assert "uv run poe check" in text
    assert "mode: fast" in text
    assert "branch `main`" in text


def test_pre_event_notice_only_before_d_day(run_hook: RunHook, git_repo: Path) -> None:
    assert "Hackathon rule" in _context(run_hook, git_repo, today=BEFORE)
    assert "Hackathon rule" not in _context(run_hook, git_repo, today=AFTER)


def test_records_baseline_fingerprint(run_hook: RunHook, git_repo: Path) -> None:
    _context(run_hook, git_repo)
    state = _common.load_state(git_repo, "session-s1")
    assert state["baseline"] == _common.tree_fingerprint(git_repo)
    assert state["blocks"] == 0


def test_warns_when_git_hooks_are_missing(run_hook: RunHook, git_repo: Path) -> None:
    assert "uv run pre-commit install" in _context(run_hook, git_repo)


def test_no_warning_when_git_hooks_are_installed(
    run_hook: RunHook, git_repo: Path, git: Git
) -> None:
    hooks_dir = Path(git(git_repo, "rev-parse", "--git-path", "hooks").strip())
    for name in session_context.GIT_HOOKS:
        (hooks_dir / name).write_text("#!/bin/sh\n# generated by pre-commit\n", encoding="utf-8")
    assert "pre-commit install" not in _context(run_hook, git_repo)


def test_warns_without_venv(run_hook: RunHook, git_repo: Path) -> None:
    assert "uv sync" in _context(run_hook, git_repo)
    (git_repo / ".venv").mkdir()
    assert "uv sync" not in _context(run_hook, git_repo)


def test_warns_without_node_modules(run_hook: RunHook, git_repo: Path) -> None:
    assert "pnpm install" not in _context(run_hook, git_repo)  # no package.json: nothing to do
    (git_repo / "package.json").write_text("{}", encoding="utf-8")
    assert "pnpm install" in _context(run_hook, git_repo)
    (git_repo / "node_modules").mkdir()
    assert "pnpm install" not in _context(run_hook, git_repo)


def test_works_outside_git(run_hook: RunHook, tmp_path: Path) -> None:
    text = _context(run_hook, tmp_path)
    assert "detached/unknown" in text
    assert session_context.missing_git_hooks(tmp_path) == list(session_context.GIT_HOOKS)


def test_fails_open_on_bad_payload(run_hook: RunHook) -> None:
    res = run_hook(session_context.main, "{nope")
    assert res.code == 0
    assert "skipped" in res.stderr
